import random

tango = {
    # Module1
    'define' : '定义，解释',
    'question' : '怀疑，表示疑问',
    'origin' : '源头，起源',
    'hypothesis' : '假设，假说',
    'refute' : '驳斥',
    'specialize' : '专门研究，专攻',
    'fundamental' : '基础的',
    'evolution' : '进化',
    'microbiology' : '微生物学',
    'zoology' : '动物学',
    'psychology' : '心理学',
    'sociology' : '社会学',
    'anthropology' : '人类学',
    'physical science' : '自然科学',
    
    'accuracy' : '准确，精确',
    'attribute' : '属性，特性',
    'prevailing' : '普遍的，盛行的',
    'technical' : '专业的，专科的',
    'undermine' : '逐渐削弱',
    'suspicion' : '怀疑',
    'explosive' : '炸药，爆炸物',
    'ascertain' : '查明，弄清',
    'consequence' : '结果，后果',
    'proposition' : '提议，建议',
    'devise' : '构想，设计',
    'formulate' : '构想出（计划或提案）',
    'deduction' : '推演，演绎',
    'distinction' : '区别',
    'productive' : '生产力高的',
    'application' : '应用',
    'precept' : '准则，规范',
    'accumulate' : '积累',
    'inquire' : '查询，调查',
    'motion' : '运动，移动',
    'composition' : '成分，构成',
    'disciple' : '信徒，追随者',
    'astronomy' : '天文学',
    'infinitely' : '无限地',
    'geology' : '地质学',
    'particle' : '例子；微粒',
    'immense' : '极大的，巨大的',
    'modus vivendi' : '妥协',
    'celestial body' : '天体',
    'of little/no avail' : '没用',
    'be apt to' : '倾向于',
    'for the sake of' : '为了',
    'in regard to' : '关于，至于',
    'with referrence to' : '遵照',
    
    # Module2
    'nuclear' : '核的，核武器的',
    'circuit' : '电路',
    'electricity' : '电',
    'leftover' : '剩余的',
    
    'silicon' : '硅',
    'savvy' : '洞察力，见解',
    'verify' : '证实',
    'ventilation' : '通风',
    'spectrum' : '光谱；范围',
    'infrastructure' : '基础设施',
    'construct' : '建造',
    'electronic' : '电子的',
    'transform' : '改变，转变',
    'implement' : '实现，实施，执行',
    'abstract' : '抽象的',
    'emission' : '排放',
    'commercial' : '商业的',
    'rational' : '理性的',
    'civil engineering' : '土木工程',
    'electrical engineering' : '电气工程',
    'reinforced concrete' : '钢筋混凝土',
    
    # Module3
    'advocate' : '拥护者，支持者',
    'entity' : '实体',
    'generator' : '生成器；促使...发生的人',
    'geometry' : '几何',
    'manifestation' : '显示，表明',
    'discern' : '察觉出，识别',
    'proponent' : '倡导者',
    'laureate' : '荣誉获得者',
    'axiomatizev' : '使公理化',
    'coin' : '创造',
    'boast' : '自夸',
    'cryptography' : '密码学',
    'sequence' : '序列',
    'unravel' : '阐释，说明',
    'replication' : '复制',
    'stumble upon' : '偶遇，偶然发现',
    'number theory' : '数论',
    'string theory' : '弦理论，弦论',
    'knot theory' : '结理论，纽结理论',
    
    'comparable' : '可比的，相当的',
    'handmaiden' : '女佣人，侍女',
    'occasionally' : '偶然',
    'affluent' : '富裕的',
    'doctrine' : '教义，主义，学说',
    'instrinsic' : '内在的，本质的',
    'insciribe' : '在...上写；题；刻',
    'ignorant' : '无知的',
    'academy' : '研究院',
    'anguish' : '剧痛，极度痛苦',
    'gist' : '要点，主旨',
    'compexity' : '复杂性',
    'advance' : '（知识）发展，进展',
    'property' : '性质，特性',
    'baffle' : '使困惑',
    'crystallize' : '使成型，具体化',
    'predecessor' : '前任，前辈',
    'genius' : '天资，天才',
    'credit' : '赞扬',
    'indubitable' : '明确无疑的',
    'formula' : '公式；方案',
    'calculus' : '微积分',
    'analytic geometry' : '解析几何',
    'integral calculus' : '积分学',
    'differential calculus' : '微分学',
    'catch a glimpse of' : '瞥见',
    'by a stretch of imagination' : '想入非非',
    'attend to' : '处理；注意',
    'take shape' : '成型，形成',
    'in the air' : '可感觉到；悬而未决的',
    'down to earth' : '务实的，脚踏实地的',
    'ascribe to' : '把...归于...'
}

def rd_choose(n:int=4) -> list[tuple]:
    answer_ls = random.sample(tango.items(), n)
    return answer_ls
